---
# Common settings for Spring Boot

# Spring Boot options
spring:
    # Watching Static Resource Change
    devtools:
        livereload:
            enabled: false
    # Default Profile is local
    # Profiles : local
    profiles:
        active: local
    # * Spring output logs colorize
    output:
        ansi:
            enabled: always
    # ! Thymeleaf (Server Side Template Engine) Configuration
    thymeleaf:
        prefix: classpath:/templates/   # ! Config for using ViewResolver
        suffix: .html                   # ! Thymeleaf view template file extension config, Default : *.html
        cache: false                    # ! Don't remain thymeleaf template cache
        check-template-location: true   # ! Template directory files exist check, Default : true
        reactive:
            max-chunk-size: 8192
          