apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - boardFe-svc-np.yaml

namespace: board-fe

images:
  - name: fsdp/board-fe
    newName: docker.io/fsdp/board-fe
    newTag: 1.0.0.prod-k3d-np

commonLabels:
  app: board-fe