apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base
  - boardFe-svc.yaml
  - boardFe-ingress.yaml

namespace: board-fe

images:
  - name: fsdp/board-fe
    newName: docker.io/fsdp/board-fe
    newTag: 1.0.0.prod-kind-ingress

commonLabels:
  app: board-fe